config:
  azure-native:location: eastus2
  cani-workload:platformStackRef: jasonbrookecarney-gmail-com/cani-platform/dev
  cani-workload:aadAdminGroupObjectIds:
    - 9b14372c-a8ab-4d09-822d-578178fb0812
